"""Initial Tshivenda heritage entries to seed the Evenda encyclopedia."""

SEED_ENTRIES = [
    {
        "term": "Ndaa",
        "translation": "Greeting (used by men) — 'Hello/Greetings'",
        "pronunciation": "n-daah",
        "category": "words",
        "meaning": "A respectful Tshivenda greeting traditionally used by men. The female counterpart is 'Aa'. It conveys deep respect when addressing elders or peers.",
        "example": "When a young Venda man meets his elder, he says 'Ndaa, Vho-Khotsi' (Greetings, father).",
        "region": "Vhembe (general Venda)",
    },
    {
        "term": "Aa",
        "translation": "Greeting (used by women) — 'Hello/Greetings'",
        "pronunciation": "ah-ah",
        "category": "words",
        "meaning": "The traditional Tshivenda greeting used by women, paired with a slight bow or curtsy when addressing elders. The masculine equivalent is 'Ndaa'.",
        "example": "Mufunzi a tshi swika nḓuni, o ri 'Aa!' (When the teacher arrived at home, she said 'Aa!').",
        "region": "Vhembe (general Venda)",
    },
    {
        "term": "Muthu ndi muthu nga vhanwe",
        "translation": "A person is a person because of others",
        "pronunciation": "moo-thoo n-dee moo-thoo nga vha-nweh",
        "category": "proverbs",
        "meaning": "The Tshivenda expression of Ubuntu — our humanity is realised through community. Personhood is shaped by relationships, not isolation.",
        "example": "Used to remind someone to help a neighbour: 'Muthu ndi muthu nga vhanwe — we rise together.'",
        "region": "Limpopo",
    },
    {
        "term": "Tshilidzi tshi a fhumudza",
        "translation": "Patience cools things down",
        "pronunciation": "tshee-lee-dzee tshee ah foo-moo-dza",
        "category": "proverbs",
        "meaning": "An idiom encouraging patience in conflict. Acting in haste worsens a situation; quiet patience resolves it.",
        "example": "After a heated argument, an elder says: 'Tshilidzi tshi a fhumudza — give it time.'",
        "region": "Vhembe",
    },
    {
        "term": "U vhofha mutuka",
        "translation": "To tie the knot (literally: to tie a young man)",
        "pronunciation": "oo voh-fah moo-too-ka",
        "category": "idioms",
        "meaning": "An idiomatic phrase referring to a woman getting married — symbolising the union and commitment between the families.",
        "example": "Vho vhofha mutuka nga Mugivhela. (They tied the knot on Saturday.)",
        "region": "Vhembe",
    },
    {
        "term": "Muri wa Muvhuyu",
        "translation": "Baobab Tree",
        "pronunciation": "moo-ree wah moo-vhoo-yoo",
        "category": "plants",
        "meaning": "The iconic baobab tree, sacred to Venda people. Known as the 'tree of life', its fruit is used for food and medicine, and the bark is used for fibre and crafts.",
        "example": "Muvhuyu u na zwiḽiwa zwa ndeme — 'The baobab has important food.'",
        "region": "Limpopo lowveld, Musina",
    },
    {
        "term": "Mutshato",
        "translation": "Marula Tree",
        "pronunciation": "moo-tsha-toh",
        "category": "plants",
        "meaning": "The marula tree, treasured for its sweet yellow fruit used in brewing traditional beer (mukumbi). Considered sacred and often associated with fertility ceremonies.",
        "example": "Mukumbi u itwa nga mitshato. (Marula beer is made from marulas.)",
        "region": "Vhembe, Mopani",
    },
    {
        "term": "Ndou",
        "translation": "Elephant",
        "pronunciation": "n-doh",
        "category": "animals",
        "meaning": "The elephant, a totem animal (mutupo) for some Venda clans, especially the Vhasenzi. Symbol of strength, wisdom, and royalty.",
        "example": "Vhuhosi ha vhone vhu fanyiswa na ndou. (Their kingship is likened to the elephant.)",
        "region": "Kruger region, Mapungubwe",
    },
    {
        "term": "Tshivhada",
        "translation": "Lion",
        "pronunciation": "tshee-vha-da",
        "category": "animals",
        "meaning": "The lion. In Venda folklore, the lion appears as a fearsome figure of authority and danger, often invoked in warning tales told to children.",
        "example": "Tshivhada tshi a fhanyiswa na khosi. (The lion is likened to a king.)",
        "region": "Limpopo",
    },
    {
        "term": "Thohoyandou",
        "translation": "Head of the elephant — capital of Vhembe",
        "pronunciation": "toh-hoh-yan-doh",
        "category": "places",
        "meaning": "The administrative capital of the former Venda homeland and a major town in Limpopo, named after the legendary Venda king Thohoyandou ('head of the elephant').",
        "example": "Ndi a ya Thohoyandou ngomu mara. (I am going to Thohoyandou tomorrow.)",
        "region": "Vhembe District",
    },
    {
        "term": "Dzata",
        "translation": "Royal Capital of Singo Dynasty",
        "pronunciation": "dza-tah",
        "category": "places",
        "meaning": "The historical stone-walled capital of the Singo dynasty in the 17th century, now an important Venda heritage site near Nzhelele Valley.",
        "example": "Dzata ndi fhethu ha vhuhosi ha kale. (Dzata is a place of ancient kingship.)",
        "region": "Nzhelele Valley",
    },
    {
        "term": "Khosi Thohoyandou",
        "translation": "King Thohoyandou",
        "pronunciation": "ko-see toh-hoh-yan-doh",
        "category": "people",
        "meaning": "The legendary 18th-century Venda king who unified the Venda nation. His name 'head of the elephant' signifies wisdom and unmatched authority. He is said to have vanished mysteriously, leaving only his royal drum, Ngoma Lungundu.",
        "example": "Khosi Thohoyandou o vhumba lushaka lwa Vhavenda. (King Thohoyandou built the Venda nation.)",
        "region": "Dzata",
    },
    {
        "term": "Domba",
        "translation": "Python Dance / Coming-of-age Ceremony",
        "pronunciation": "dom-ba",
        "category": "customs",
        "meaning": "A traditional pre-marital initiation dance for young Venda women. Dancers form a long chain mimicking a python's movement — a sacred celebration of fertility, womanhood, and community.",
        "example": "Vhasidzana vha tshi tamba domba ngomu vhuṱambo. (The girls dance the domba during the festival.)",
        "region": "Vhembe",
    },
    {
        "term": "U Phasa",
        "translation": "Ancestor Veneration Ritual",
        "pronunciation": "oo pa-sa",
        "category": "customs",
        "meaning": "A sacred Venda ritual in which elders speak to and honour the ancestors (vhadzimu) using snuff, traditional beer, and prayer — to seek guidance, healing, or blessing.",
        "example": "Vho-Khotsi vha phasa nga matsheloni. (Father performs the phasa ritual in the morning.)",
        "region": "All Venda areas",
    },
    {
        "term": "Ngoma Lungundu",
        "translation": "The Drum That Thunders",
        "pronunciation": "n-go-ma loon-goon-doo",
        "category": "folklore",
        "meaning": "The mystical sacred drum of the Venda people, said to have been brought from the north by their ancestors. According to legend, when struck it would thunder so loudly it could destroy enemies. It is the central symbol of Venda spiritual heritage.",
        "example": "Ngoma Lungundu yo vha i tshi pfi nga muvhuso. (Ngoma Lungundu was heard across the kingdom.)",
        "region": "Mythical / Dzata",
    },
]
